#!/bin/sh

# usage: ln -fs ../../pre-commit .git/hooks/pre-commit

# put stuff to do before committing here

harp compile
[ $? -ne 0 ] && exit 1


surge www -d muchanem.surge.sh
[ $? -ne 0 ] && exit 1
exit 0

